- name: Setup Abiotic Factor game server
  hosts: Winston
  vars:
        lxc_vmid: 404
        MaxServerPlayers: 6
        ServerName: "Abiotic"
        SaveName: "Abiotic"

  roles:
    - role: proxmox_lxc
      vars:
        lxc_hostname: "Abiotic-Server"
        lxc_memory: 8192
        lxc_cores: 4
        lxc_netif: "{'net0': 'name=eth0,bridge=vmbr0,ip=10.69.1.40/24,gw=10.69.1.1'}"
        lxc_tags: "gameserver"
        lxc_disk: 'local-lvm:30'
        lxc_template: "local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
        lxc_state: present
    
    - role: proxmox_lxc
      vars:
        lxc_hostname: "Abiotic-Server"
        lxc_memory: 8192
        lxc_cores: 4
        lxc_netif: "{'net0': 'name=eth0,bridge=vmbr0,ip=10.69.1.40/24,gw=10.69.1.1'}"
        lxc_tags: "gameserver"
        lxc_disk: 'local-lvm:30'
        lxc_template: "local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
        lxc_state: started
        

  tasks:

    - name: Check container status
      shell: "pct status {{lxc_vmid}}"
      register: container_status

    - name: Debug container status
      debug:
        var: container_status.stdout

    - name: install abiotic on {{lxc_vmid}} and install server files
      vars:
        bash: "pct exec {{lxc_vmid}} -- bash -c"
      shell: |
        pct exec {{lxc_vmid}} -- bash <<'EOF'
          useradd -m abiotic
          apt update -y 
          apt upgrade -y
          apt install software-properties-common lsb-release wget -y
          mkdir -pm777 /etc/apt/keyrings
          wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/dists/$(lsb_release -cs)/winehq-$(lsb_release -cs).sources
          dpkg --add-architecture i386
          apt update -y
          apt install --install-recommends winehq-staging -y
          apt install cabextract winbind screen xvfb -y
          ln -sf /opt/wine-staging/bin/wine64 /usr/local/bin/wine64
          ln -sf /opt/wine-staging/bin/wine /usr/local/bin/wine
          add-apt-repository multiverse -y
          apt install libegl1 libegl-mesa0 libgles2 -y
          apt update -y

          # Pre-accept Steam license
          echo steam steam/question select "I AGREE" | debconf-set-selections
          echo steam steam/license note '' | debconf-set-selections

          apt install steamcmd -y
          mkdir /home/abiotic/abioticserver
          chown -R abiotic:abiotic /home/abiotic


          su - abiotic -c 'WINEARCH=win64 WINEPREFIX=/home/abiotic/.wine xvfb-run wineboot --init'
          su - abiotic -c '/usr/games/steamcmd +force_install_dir /home/abiotic/abioticserver +login anonymous +@sSteamCmdForcePlatformType windows +@sSteamCmdForcePlatformBitness +app_update 2857200 validate +quit'
        EOF
      register: setup_result


    - name: Render config template locally
      template:
        src: "{{ playbook_dir }}/mytemplates/abiotic_run_server.sh.j2"
        dest: "/tmp/abiotic_runserver.sh"
      delegate_to: localhost

    - name: Copy rendered script to Proxmox host
      copy:
        src: "/tmp/abiotic_runserver.sh"
        dest: "/tmp/abiotic_runserver.sh"

    - name: Copy config into container
      shell: "pct push {{ lxc_vmid }} /tmp/abiotic_runserver.sh /home/abiotic/abioticserver/AbioticFactor/Binaries/Win64/runserver.sh --perms 0744 --user 1000"

    - name: Show output
      debug:
        var: setup_result.stdout_lines
