- name: Setup Factorio game server
  hosts: Winston
  vars:
        lxc_vmid: 404
        mod_list:
          - base
          - quality
          - space-age

  roles:
    - role: proxmox_lxc
      vars:
        lxc_hostname: "Factorio-Server"
        lxc_memory: 8192
        lxc_cores: 4
        lxc_netif: "{'net0': 'name=eth0,bridge=vmbr0,ip=10.69.1.39/24,gw=10.69.1.1'}"
        lxc_tags: "gameserver"
        lxc_disk: 'local-lvm:30'
        lxc_template: "local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
        lxc_state: present
    
    - role: proxmox_lxc
      vars:
        lxc_hostname: "Factorio-Server"
        lxc_memory: 8192
        lxc_cores: 4
        lxc_netif: "{'net0': 'name=eth0,bridge=vmbr0,ip=10.69.1.39/24,gw=10.69.1.1'}"
        lxc_tags: "gameserver"
        lxc_disk: 'local-lvm:30'
        lxc_template: "local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
        lxc_state: started
        

  tasks:

    - name: Check container status
      shell: "pct status {{lxc_vmid}}"
      register: container_status

    - name: Debug container status
      debug:
        var: container_status.stdout

    - name: install Factorio on {{lxc_vmid}} and install server files
      vars:
        bash: "pct exec {{lxc_vmid}} -- bash -c"
      shell: |
        set -e
        useradd -m factorio --disabled-login --no-create-home --gecos
        apt update -y 
        apt upgrade -y
        wget -O /opt/factorio_headless.tar.gz https://www.factorio.com/get-download/latest/headless/linux64
        tar -xvf /opt/factorio_headless.tar.gz
        rm /opt/factorio_headless.tar.gz
        chown -R factorio:factorio /opt/factorio
        rm /opt/factorio/mods/mod-list.json
        
        EOF
      register: setup_result

    - name: Build mod list
      set_fact:
        mod_json:
          mods: "{{ mod_list | map('community.general.dict_kv', 'name') | map('combine', {'enabled': true}) | list }}"

    - name: Copy mod config into container
      shell: "pct push {{ lxc_vmid }} {{ mod_json | to_nice_json }} /opt/factorio/mods/mod-list.json --perms 0700 --user 1000"

    - name: Example clone of a single branch
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/crash8229/factorio-mod-downloader/blob/main/factorio_mod_downloader.py"
        dest: /tmp/script.py
        mode: '0755'

    - name: Push script into container
      ansible.builtin.command:
        cmd: "pct push {{ lxc_vmid }} /tmp/script.py /opt/scripts/script.py --perms 0755"

    - name: Clean up temp file on host
      ansible.builtin.file:
        path: /tmp/script.py
        state: absent

    - name: Install pip in container
      ansible.builtin.command:
        cmd: "pct exec {{ lxc_vmid }} -- apt install -y python3-pip"

    - name: Run script in container
      ansible.builtin.command:
        cmd: "pct exec {{ lxc_vmid }} -- python3 /opt/scripts/script.py /opt/factorio/mods/mod-list.json"